import {SeparatorMenuItem, type MenuItem} from '../../menus/core'
import {
    AudioMenuItem,
    AttachmentMenuItem,
    BlockquoteMenuItem,
    BoldMenuItem,
    BulletListMenuItem,
    ClearFormattingMenuItem,
    BackgroundColorMenuItem,
    CodeBlockMenuItem,
    DetailsMenuItem,
    EmojiMenuItem,
    HighlightBlockMenuItem,
    HorizontalRuleMenuItem,
    ImageMenuItem,
    InlineCodeMenuItem,
    FontFamilyMenuItem,
    FontColorMenuItem,
    FontSizeMenuItem,
    FormulaMenuItem,
    FormatPainterMenuItem,
    FullscreenMenuItem,
    HighlightColorMenuItem,
    DecreaseIndentMenuItem,
    IncreaseIndentMenuItem,
    LetterSpacingMenuItem,
    LineHeightMenuItem,
    ItalicMenuItem,
    LinkMenuItem,
    OrderedListMenuItem,
    PasteMenuItem,
    PrintMenuItem,
    RedoMenuItem,
    StrikethroughMenuItem,
    TableMenuItem,
    TaskListMenuItem,
    TextStyleMenuItem,
    SubscriptMenuItem,
    SuperscriptMenuItem,
    TextAlignMenuItem,
    UnderlineMenuItem,
    UndoMenuItem,
    VideoMenuItem,
    type EmojiMenuItemOptions,
    type FontFamilyOption,
    type FontSizeOption,
    type FullscreenMenuItemOptions,
    type HighlightBlockMenuOptions,
    type LineHeightOption,
    type LetterSpacingSetting,
    type LinkMenuItemOptions,
    type PrintMenuItemOptions,
    type TextColorPaletteSetting,
    type TextAlignmentOption,
    type TextAlignMenuOptions,
} from '../../menus/items'
import type {Uploader} from '../../uploader'
import {
    defaultFontFamilies,
    defaultFontSizes,
    defaultLetterSpacingSlider,
    defaultLineHeights,
    defaultTextAlignments
} from '../../menus/items'

/**
 * 为每个编辑器实例创建一套全新的默认工具栏项目。
 * 返回新实例而非共享单例，避免 DOM、事件和 active 状态在多个编辑器之间串联。
 */
export function createDefaultToolbarItems(
    fontFamilies: false | FontFamilyOption[] = defaultFontFamilies,
    fontSizes: false | FontSizeOption[] = defaultFontSizes,
    letterSpacings: false | LetterSpacingSetting = defaultLetterSpacingSlider,
    lineHeights: false | LineHeightOption[] = defaultLineHeights,
    textAlignments: false | TextAlignmentOption[] | TextAlignMenuOptions = defaultTextAlignments,
    fontColors: false | TextColorPaletteSetting = {},
    backgroundColors: false | TextColorPaletteSetting = {},
    highlightColors: false | TextColorPaletteSetting = {},
    indentation = true,
    highlightBlock: false | HighlightBlockMenuOptions = {},
    uploader?: Uploader,
    link: LinkMenuItemOptions = {},
    emoji: false | EmojiMenuItemOptions = {},
    fullscreen?: FullscreenMenuItemOptions,
    print: PrintMenuItemOptions = {},
): MenuItem[] {
    return [
        // 文本样式与段落排版；false 配置用于从默认工具栏中按能力裁剪。
        new TextStyleMenuItem(),
        ...(fontFamilies === false ? [] : [new FontFamilyMenuItem(fontFamilies)]),
        ...(fontSizes === false ? [] : [new FontSizeMenuItem(fontSizes)]),
        ...(letterSpacings === false ? [] : [new LetterSpacingMenuItem(letterSpacings)]),
        ...(fontColors === false ? [] : [new FontColorMenuItem(fontColors)]),
        ...(backgroundColors === false ? [] : [new BackgroundColorMenuItem(backgroundColors)]),
        ...(highlightColors === false ? [] : [new HighlightColorMenuItem(highlightColors)]),
        ...(lineHeights === false ? [] : [new LineHeightMenuItem(lineHeights)]),
        ...(textAlignments === false ? [] : [new TextAlignMenuItem(textAlignments)]),
        ...(indentation ? [new DecreaseIndentMenuItem(), new IncreaseIndentMenuItem()] : []),
        new SeparatorMenuItem('separator-text'),
        // 高频行内格式。
        new BoldMenuItem(),
        new ItalicMenuItem(),
        new UnderlineMenuItem(),
        new StrikethroughMenuItem(),
        new InlineCodeMenuItem(),
        new SuperscriptMenuItem(),
        new SubscriptMenuItem(),
        new SeparatorMenuItem('separator-block'),
        // 块结构与富内容插入。
        new BulletListMenuItem(),
        new OrderedListMenuItem(),
        new TaskListMenuItem(),
        new BlockquoteMenuItem(),
        ...(highlightBlock === false ? [] : [new HighlightBlockMenuItem(highlightBlock)]),
        new CodeBlockMenuItem(),
        new DetailsMenuItem(),
        new FormulaMenuItem(),
        ...(emoji === false ? [] : [new EmojiMenuItem(emoji)]),
        new ImageMenuItem({uploader}),
        new AudioMenuItem({uploader}),
        new VideoMenuItem({uploader}),
        new AttachmentMenuItem({uploader}),
        new TableMenuItem(),
        new HorizontalRuleMenuItem(),
        new SeparatorMenuItem('separator-link'),
        // 链接、格式辅助与编辑器级操作。
        new LinkMenuItem(link),
        new FormatPainterMenuItem(),
        new ClearFormattingMenuItem(),
        new SeparatorMenuItem('separator-history'),
        new PasteMenuItem(),
        new UndoMenuItem(),
        new RedoMenuItem(),
        new PrintMenuItem(print),
        ...(fullscreen ? [new FullscreenMenuItem(fullscreen)] : []),
    ]
}

/** 兼容旧命名的别名。 */
export const createDefaultMenuItems = createDefaultToolbarItems
